my:
 greetings: full Final Updated Hello World from configclient.yml dev microService and the value is from azuremigration Brach
 list:
   values: hundred , twohundred , dev

db:
  connection: full final connectionString1dev
  host: full final localeedev
  port: 12001
